pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    stages {
        stage('Tests with simple tag') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/marcelodebittencourt/TestingMind_TAS2021_JUnit5.git'

                // To run Maven on a Windows agent, use
                bat "mvn -B test -Dgroups=Simple --file pom.xml"
            }

        }

        stage('All Tests') {
            steps {
                 // To run Maven on a Windows agent, use
                bat "mvn -B test --file pom.xml"
            }
            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
    }
}